const types = {
  FETCH_POPULATION: 'FETCH_POPULATION',
  FETCH_POPULATION_SUCCESS: 'FETCH_POPULATION_SUCCESS',
  FETCH_POPULATION_ERROR: 'FETCH_POPULATION_ERROR',
  FILTER_POPULATION_BY_NAME: 'FILTER_POPULATION_BY_NAME',
};
export default types;
